spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5433/ticketing
    username: ticketing_user
    password: ticketing_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >-
          paymentConfirmed:com.rohit.paymentservice.event.PaymentConfirmedEvent,
          paymentFailed:com.rohit.paymentservice.event.PaymentFailedEvent
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.rohit.paymentservice.event
        spring.json.type.mapping: seatReserved:com.rohit.paymentservice.event.SeatReservedEvent

server:
  port: 8083

springdoc:
  swagger-ui:
    path: /swagger-ui.html
