spring:
  application:
    name: reservation-service
  datasource:
    url: jdbc:postgresql://localhost:5433/ticketing
    username: ticketing_user
    password: ticketing_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

event-service:
  base-url: http://localhost:8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
